version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - egurinko
  assignees:
  - egurinko
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.24.2
  - dependency-name: "@babel/helper-module-imports"
    versions:
    - 7.12.13
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.2
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.8
  - dependency-name: aws-sdk
    versions:
    - 2.834.0
    - 2.853.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
